version: '2'

networks:
  app_tier:
    driver: bridge
    ipam:
     config:
       - subnet: 172.11.1.0/16
         gateway: 172.11.5.254

services:

  db:
    build: docker/db
    image: skeleton/db
    networks:
      app_tier:
        ipv4_address: 172.11.1.1
    ports:
      - "3306:3306"
    env_file:
      - ./database.env
    volumes:
      - ./logs/mysql:/var/log/mysql
      - ./db:/var/lib/mysql

  app:
    build: docker/app
    image: skeleton/app
    env_file:
      - ./app.env
    networks:
      app_tier:
        ipv4_address: 172.11.1.2
    volumes:
      - ./app:/var/www/html

  nginx:
    build: docker/nginx
    image: skeleton/nginx
    networks:
      app_tier:
        ipv4_address: 172.11.1.3
    ports:
      - "80:80"
    volumes_from:
      - app:ro
    volumes:
      - ./docker/nginx/proxy.conf:/etc/nginx/conf.d/default.conf

  selenium:
    image: selenium/standalone-chrome:latest
    networks:
      app_tier:
        ipv4_address: 172.11.1.4
